# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:
#    util.class: AppBundle\Utils\MatchUtil

services:
   game.util:
        class: AppBundle\Utils\MatchUtil
        arguments: [ @doctrine.orm.entity_manager ]
